# Generated by Django 4.2.1 on 2023-10-25 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futgoolApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='calificaciones',
            field=models.ManyToManyField(related_name='usuarios', to='futgoolApp.calificacion'),
        ),
    ]
